[client]
showErrorDetails = "none"

[theme]
# Primary accent color (used for primary buttons, active elements)
primaryColor = "#F42937"

# Main background color (Darkest background)
backgroundColor = "#1A1A1F"

# Secondary background (Used for user chat bubbles, input fields, inactive buttons)
secondaryBackgroundColor = "#3D3D4E"

# Text color (Light greyish-white)
textColor = "#ECEAF4"

# Use sans serif as the base, we will override specific elements with web fonts in app.py
font = "sans serif"